language: java
jobs:
    include:
        - if: type = push AND branch = master
          env: ARGS="-Pci.branch=master"
        - if: type = push AND branch = patch-1
          env: ARGS="-Pci.branch=patch-1"
        - if: type = pull_request
          env: ARGS="-Pci.branch=patch-1 -Pci.pr.targetBranch=master -Pci.pr=1"
        - if: tag IS present
          env: ARGS="-Pci.tag=tag-1"
script: ./gradlew check $ARGS
