name: CI master

on:
    push:
        branches:
            - master
jobs:
    build_master:
        name: Build master
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Setup java
              uses: actions/setup-java@v1
              with:
                  java-version: '1.8'
            - run: ./gradlew check -Pci.branch=master
